version: "1.0"
info:
  model: int-scaffold
packages:
- name: SttDemoiPaaSProject
  gitServerName: stt_gh
  gitUrl: https://github.com/staillansag/SttDemoiPaaSProject
  gitUsername: staillansag
  gitBranch: main
- name: WmJDBCAdapter
  wpmServer: https://packages.softwareag.com
  wpmRegistry: softwareag
- name: sttUtils
  gitServerName: stt_gh
  gitUrl: https://github.com/staillansag
  gitUsername: staillansag
  gitBranch: main
services:
- serviceName: project.sttdemoipaas.integrations:upsertContact
  packages:
  - name: SttDemoiPaaSProject
    version: "1.0"
- serviceName: project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:SqlEdgeLocal
  packages:
  - name: SttDemoiPaaSProject
    version: "1.0"
- serviceName: project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:insertAccount
  packages:
  - name: SttDemoiPaaSProject
    version: "1.0"
  - name: sttUtils
    version: "1.0"
- serviceName: project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:SQLEdgeLocalNoTransaction
  packages:
  - name: SttDemoiPaaSProject
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.741
- serviceName: project.sttdemoipaas.integrations:test
  packages:
  - name: SttDemoiPaaSProject
    version: "1.0"
- serviceName: project.sttdemoipaas.integrations:createAccount
  packages:
  - name: SttDemoiPaaSProject
    version: "1.0"
  - name: sttUtils
    version: "1.0"
- serviceName: pub.string:objectToString
  packages:
  - name: WmPublic
    version: 11.0.0.0.741
- serviceName: pub.flow:getLastFailureCaught
  packages:
  - name: WmPublic
    version: 11.0.0.0.741
- serviceName: pub.json:documentToJSONString
  packages:
  - name: WmPublic
    version: 11.0.0.0.741
- serviceName: sttUtils.services:getServerName
  packages:
  - name: sttUtils
    version: "1.0"
- serviceName: project.sttdemoipaas.integrations:selectAccountById
  packages:
  - name: SttDemoiPaaSProject
    version: "1.0"
  - name: sttUtils
    version: "1.0"
- serviceName: project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:selectAccountById
  packages:
  - name: SttDemoiPaaSProject
    version: "1.0"
  - name: sttUtils
    version: "1.0"
- serviceName: project.sttdemoipaas.integrations:updateAccount
  packages:
  - name: SttDemoiPaaSProject
    version: "1.0"
  - name: sttUtils
    version: "1.0"
- serviceName: project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:updateAccount
  packages:
  - name: SttDemoiPaaSProject
    version: "1.0"
  - name: sttUtils
    version: "1.0"
configurationVariables:
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SQLEdgeLocalNoTransaction.connectionSettings.otherProperties
  : loginTimeout=60;
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SqlEdgeLocal.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SqlEdgeLocal.connectionEnabled
  : "false"
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SqlEdgeLocal.connectionSettings.portNumber
  : "1433"
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SqlEdgeLocal.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.sqlserver.SQLServerDataSource
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SQLEdgeLocalNoTransaction.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SQLEdgeLocalNoTransaction.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SqlEdgeLocal.connectionManagerSettings.poolable
  : "false"
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SQLEdgeLocalNoTransaction.connectionSettings.portNumber
  : "1433"
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SQLEdgeLocalNoTransaction.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SQLEdgeLocalNoTransaction.connectionEnabled
  : "false"
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SQLEdgeLocalNoTransaction.connectionSettings.driverType
  : Progress速 DataDirect速
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SQLEdgeLocalNoTransaction.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SQLEdgeLocalNoTransaction.connectionSettings.password
  : "{AES}M1eQ3ETXUuR98whgOwcRBA=="
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SQLEdgeLocalNoTransaction.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SqlEdgeLocal.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SQLEdgeLocalNoTransaction.connectionSettings.user
  : sa
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SQLEdgeLocalNoTransaction.connectionSettings.serverName
  : sqlserver
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SqlEdgeLocal.connectionSettings.driverType
  : Progress速 DataDirect速
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SQLEdgeLocalNoTransaction.connectionSettings.databaseName
  : sandbox
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SqlEdgeLocal.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SQLEdgeLocalNoTransaction.connectionManagerSettings.poolable
  : "false"
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SQLEdgeLocalNoTransaction.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SqlEdgeLocal.connectionSettings.databaseName
  : sandbox
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SqlEdgeLocal.connectionManagerSettings.minimumPoolSize
  : "0"
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SqlEdgeLocal.connectionSettings.transactionType
  : LOCAL_TRANSACTION
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SQLEdgeLocalNoTransaction.connectionSettings.trustStore
  : ""
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SqlEdgeLocal.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SQLEdgeLocalNoTransaction.connectionManagerSettings.minimumPoolSize
  : "0"
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SqlEdgeLocal.connectionSettings.user
  : sa
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SqlEdgeLocal.connectionSettings.otherProperties
  : loginTimeout=60;
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SqlEdgeLocal.connectionSettings.trustStore
  : ""
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SqlEdgeLocal.connectionSettings.keyStore
  : ""
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SqlEdgeLocal.connectionSettings.serverName
  : sqlserver
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SqlEdgeLocal.connectionSettings.dbType
  : MSSQL
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SQLEdgeLocalNoTransaction.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SqlEdgeLocal.connectionSettings.password
  : "{AES}M1eQ3ETXUuR98whgOwcRBA=="
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SqlEdgeLocal.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SqlEdgeLocal.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SqlEdgeLocal.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SqlEdgeLocal.connectionSettings.networkProtocol
  : ""
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SQLEdgeLocalNoTransaction.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SQLEdgeLocalNoTransaction.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.sqlserver.SQLServerDataSource
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SQLEdgeLocalNoTransaction.connectionSettings.dbType
  : MSSQL
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SQLEdgeLocalNoTransaction.connectionSettings.keyStore
  : ""
  ? artConnection.SttDemoiPaaSProject.project.sttdemoipaas.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SQLEdgeLocalNoTransaction.connectionSettings.networkProtocol
  : ""
