version: "1.0"
info:
  model: int-scaffold
packages:
- name: SttDemoiPaaSProject
  gitServerName: stt_gh
  gitUrl: https://github.com/staillansag/SttDemoiPaaSProject
  gitUsername: staillansag
  gitBranch: main
services:
- serviceName: project.sttdemoipaas.integrations:upsertContact
  packages:
  - name: SttDemoiPaaSProject
    version: "1.0"
